### ISSUE TITLE
Order dependency upgrades lexicographically

### ISSUE THREAD

**Issue by snicoll** [spring-io/github-release-notes-generator#20]
Given that our dependency upgrades follow the same pattern thanks to `bomr`, it would be nice to order them lexicographically. It is much easier to spot a particular upgrade and things that are linked together as they probably share a prefix are naturally grouped as well.

It probably makes less sense for the other sections so it might seem a bit odd though.

**Comment by wilkinsona** [comment]
I don't think the generator should express an opinion about the ordering of the issues in a particular section as it would be making too many assumptions. Instead, it could offer a configuration option that allowed the ordering to be configured in the `sections` YAML. FWIW, I'm not totally sure I'd use the configuration option if it was there. I like the current ordering by issue number and that it's consistent across sections.

**Comment by snicoll** [comment]
Yep, you're right.
