### ISSUE TITLE
Add a LICENSE.txt file to the root of the repository

### ISSUE THREAD

**Issue by lusoalex** [spring-io/github-release-notes-generator#29]
Hello,
Could you please add a license on your repository?
Do you expect to use Apache V2 as for some others spring-io projects?
Regards,
Alexandre.

**Comment by wilkinsona** [comment]
The code is already Apache V2-licensed as per the header in each `.java` file. We can certainly add a license file to the root of the repo as well though to make that clear.

**Comment by lusoalex** [comment]
> The code is already Apache V2-licensed as per the header in each `.java` file. We can certainly add a license file to the root of the repo as well though to make that clear.

Thanks for your answer, as there was a License.txt on the others spring-io repositories, I thought that it would be great to do so in this repo too.
We have created a [Github Action to automatically push a release note](https://github.com/Decathlon/release-notes-generator-action) on a wiki when we close a milestone, so I prefer to ensure our dependencies ;)
Thanks again,
Alexandre.
