### ISSUE TITLE
Allow an issue to appear in multiple sections

### ISSUE THREAD

**Issue by eleftherias** [spring-io/github-release-notes-generator#37]
The release notes sections are not always mutually exclusive and it is possible an issue can belong to more than one section.

For example, in Spring Security, we call out any issues that break passivity in a "Non-passive" section.
These issues are also enhancements or bugs and we would like them to be listed under "New Features" or "Bug Fixes" as well.

**Comment by eleftherias** [comment]
I am happy to submit a PR if this feature request is approved.

**Comment by mbhave** [comment]
I think this is an enhancement that we could support. Maybe it should be configurable in case someone wants to avoid duplication across sections.

**Comment by wilkinsona** [comment]
Closing in favour of #37.
