### ISSUE TITLE
Escape @ in issue titles

### ISSUE THREAD

**Issue by philwebb** [spring-io/github-release-notes-generator#40]
An issue title that includes an annotation will be written directly to the release notes. This might link to a user. We could backtick them automatically.

**Comment by mbhave** [comment]
hmm, I thought we do that already https://github.com/spring-io/github-release-notes-generator/pull/22/files

**Comment by philwebb** [comment]
I just edited https://github.com/spring-projects/spring-boot/releases/tag/v2.2.7.RELEASE. Perhaps we're on an old version.

**Comment by mbhave** [comment]
yeah, we're on [0.0.2](https://github.com/spring-projects/spring-boot/blob/8eec9cf32f6d354eceabf05a1967066405a2ae4b/ci/tasks/generate-release-notes.yml#L7).
